
language: cpp
dist: trusty

addons:
  apt:
    packages:
      - libsqlite3-dev

before_script:
  - ./autogen.sh
  - ./configure

script: make && make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

